// Copyright (c) Brian Reichle.  All Rights Reserved.  Licensed under the MIT License.  See License.txt in the project root for license information.
using System;

namespace HexView.Plugins.Sample.PE
{
	[Flags]
	enum IMAGE_DLL_CHARATERISTICS : ushort
	{
		IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE = 0x0040,
		IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY = 0x0080,
		IMAGE_DLLCHARACTERISTICS_NX_COMPAT = 0x0100,
		IMAGE_DLLCHARACTERISTICS_NO_ISOLATION = 0x0200,
		IMAGE_DLLCHARACTERISTICS_NO_SEH = 0x0400,
		IMAGE_DLLCHARACTERISTICS_NO_BIND = 0x0800,
		IMAGE_DLLCHARACTERISTICS_WDM_DRIVER = 0x2000,
		IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x8000,
	}
}
